apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.label }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.zookeeper.weight }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.label }}
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "{{ .Values.zookeeper.port }}"
        - name: ZOOKEEPER_TICK_TIME
          value: "{{ .Values.zookeeper.tickTime }}"
        image: {{ .Values.zookeeper.image.name }}:{{ .Values.zookeeper.image.tag }}
        imagePullPolicy: {{ .Values.zookeeper.pullPolicy }}
        name: {{ .Values.zookeeper.label }}
        ports:
          - containerPort: {{ .Values.zookeeper.port }}
        resources:
          limits:
            memory: {{ .Values.zookeeper.resources.limits.memory }}
            cpu: {{ .Values.zookeeper.resources.limits.cpu }}
