apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.label }}-service
spec:
  selector:
    app: {{ .Values.zookeeper.label }}
  ports:
  - port: {{ .Values.zookeeper.port }}
    targetPort: {{ .Values.zookeeper.port }}