version: '3.8'

services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:7.0
    ports:
      - "27017:27017"
  web-api:
    hostname: web-api
    container_name: web-api
    image: web-api:latest
    ports:
      - "8080:8080"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - RUST_BACKTRACE=1
      - DB_CONNECTION_STRING=mongodb://mongo:27017/test