[package]
name = "domain"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
bson = { workspace = true }

