[package]
name="acl"
version="0.0.1"
edition="2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
tokio = { version = "1.33.0", features = ["full"] }
messaging = { path = "../messaging" }
domain =  { path = "../domain" }