[package]
name="acl"
version="0.0.1"
edition="2021"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
messaging = { path = "../messaging" }
domain =  { path = "../domain" }