apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.label }}
spec:
  capacity:
    storage: {{ .Values.mongodb.volume.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/{{ .Values.mongodb.label }}
    type: ""