apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.label }}
spec:
  resources:
    requests:
      storage: {{ .Values.mongodb.volume.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce