apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.label }}-service
spec:
  selector:
    app: {{ .Values.mongodb.label }}
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}