[package]
name = "app"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
serde = "1.0.188"
serde_derive = "1.0.188"
domain = { path = "../domain" }
messaging = { path = "../messaging" }
utoipa = { version = "4", features = ["actix_extras"] }