[package]
name = "api"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
utoipa = { workspace = true }
domain = { path = "../domain" }
messaging = { path = "../messaging" }