apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.label }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.api.weight }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.label }}
    spec:
      containers:
      - name: {{ .Values.api.image.name }}
        image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
        readinessProbe:
          exec:
            command: 
            - sh
            - -c
            - "nc -z kafka-service 9092 || exit -1"
        env:
        - name: DB_URI
          value: {{ .Values.api.mongodb.uri }}
        - name: KAFKA_BROKERS
          value: {{ .Values.api.kafka.brokers }}
        - name: KAFKA_TOPIC
          value: {{ .Values.api.kafka.topic }}
        - name: KAFKA_GROUP_ID
          value: {{ .Values.api.kafka.group }}
        imagePullPolicy: {{ .Values.api.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.api.resources.limits.memory }}
            cpu: {{ .Values.api.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.api.port }}
