apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.label }}-service
spec:
  selector:
    app: {{ .Values.api.label }}
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}