[package]
name = "messaging"
version = "0.0.1"
edition = "2021"


[dependencies]
rdkafka = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }