[package]
name = "infra"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
mongodb = { workspace = true }
uuid = { workspace = true }
domain = { path = "../domain" }
domain_impl = { path = "../domain_impl" }
messaging = { path = "../messaging" }