mongodb:
  label: mongodb
  replicas: 1
  weight: 2
  port: 27017
  image:
    name: mongo
    tag: latest 
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
  volume:
    capacity: 1000Mi

kafka:
  label: kafka
  replicas: 1
  weight: 1
  port: 9092
  image:
    name: confluentinc/cp-kafka
    tag: 7.0.1
  pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m" 
  variables:
    brokerId: 1
    zookeeperConnect: zookeeper-service:2181
    securityProtocolMap: PLAINTEXT:PLAINTEXT
    advertisedListeners: PLAINTEXT://kafka-service:9092
    listeners: PLAINTEXT://:9092
    numPartitions: &patitions 2
    replicationFactor: 1

zookeeper:
  label: zookeeper
  replicas: 1
  weight: 0
  port: 2181
  tickTime: 2000
  image:
    name: confluentinc/cp-zookeeper
    tag: 7.0.1
  pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m" 

acl:
  label: acl
  replicas: *patitions
  weight: 3
  kafka:
    brokers: kafka-service:9092
    topic: messages
    group: acl
  image:
    name: acl
    tag: latest
  pullPolicy: Never
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m" 

api:
  label: api
  replicas: 1
  weight: 4
  port: 8080
  image:
    name: api
    tag: latest 
  pullPolicy: Never
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
  ingress:
    host: dev-wep-api.com
    ingressClassName: nginx            
  kafka:
    brokers: kafka-service:9092
    topic: messages
    group: acl
  mongodb:
    uri: mongodb://mongodb-service:27017/